### ISSUE TITLE
Mistake in test

### ISSUE THREAD

**Issue by maxtcruz** [spencerlachance/cs4500a1part2#10]
In `test_queue_string_classes()`, the assertion `t_true(p->equals(q));` is being made, but `p` and `q` are unequal at this point. `p` contains `[s2]` and `q` contains `[s1]`.

**Comment by maxtcruz** [comment]
Adding onto this, in `test_string_class()`, `t_true(s->equals(s2));` is not true. You're assuming that `s` is being mutated as a result of `s->concat(s1);`. But, according to your spec for `string.h`, the concatenation returns a pointer to a new string, which, in your test, is never being captured. So the concatenation in your test is basically doing nothing.

**Comment by spencerlachance** [comment]
Fixed
