### ISSUE TITLE
Standardizing object.h and string.h

### ISSUE THREAD

**Issue by maxtcruz** [spencerlachance/cs4500a1part2#11]
Can we try to just use the definitions of string and object that Jan provided us:
https://piazza.com/class/k51bluky59n2jr?cid=330

https://piazza.com/class/k51bluky59n2jr?cid=166

**Comment by spencerlachance** [comment]
Why those and not these?
https://piazza.com/class/k51bluky59n2jr?cid=345

Jan himself said that we shouldn't be caching the hash codes.

**Comment by spencerlachance** [comment]
Also this conflicts with this prior issue: https://github.com/spencerlachance/cs4500a1part2/issues/2

So you guys have to agree on something

**Comment by seanolly** [comment]
it seems most of the class is intent on using Jan's provided interfaces (on Piazza), to resolve these conflicts; we suggest changing your object & string interfaces to Jan's, and to spread the adoption of Jan's interfaces to your 3 other peers that are giving you their interfaces

**Comment by seanolly** [comment]
Yes, hash codes should not be cached in an interface - that is definitely an implementation detail

**Comment by spencerlachance** [comment]
Alright Jan it is
