### ISSUE TITLE
Tests for String

### ISSUE THREAD

**Issue by grahamwren** [spencerlachance/cs4500a1part2#13]
Adding tests for String and Object outside of the interface required to implement Queue increases interdependence between our code which is not relevant to the assignment. I don't see anywhere in the assignment which asks you to provide these tests and the implementers of your interface are going to bring their String and Object classes anyway. Please only test methods which are included in your chosen interface, or which are required to test your chosen interface.

**Comment by grahamwren** [comment]
Asked in class, here is the response: https://piazza.com/class/k51bluky59n2jr?cid=305
Will open a PR to remove these tests.

**Comment by spencerlachance** [comment]
Piazza link is wrong but I found the right post, you're good to go!
