### ISSUE TITLE
int -> size_t

### ISSUE THREAD

**Issue by maxtcruz** [spencerlachance/cs4500a1part2#16]
Can `get_queue_length()` return a `size_t` instead of an `int`?

**Comment by grahamwren** [comment]
Per the [Google C++ Style Guide](https://google.github.io/styleguide/cppguide.html#Integer_Types)

> Of the C integer types, only int should be used. When appropriate, you are welcome to use standard types like size_t and ptrdiff_t.

However, to further specify when unsigned types are appropriate they say:

> try to avoid unsigned types (except for representing bitfields or modular arithmetic). Do not use an unsigned type merely to assert that a variable is non-negative.

In my own experience, there is no benefit to using the `size_t` type and signed/unsigned errors are sufficiently common that you're better off avoiding it.
