### ISSUE TITLE
String/Object Classes

### ISSUE THREAD

**Issue by dxandbatista** [spencerlachance/cs4500a1part2#18]
Hey,

Seems like there's a united push for the entire class to use Chase Bishop's versions of Object/String, it'd be great if it could be implemented here as well as the other two specs we're working with have already done the same.

https://github.com/chasebish/cwc_object_string

Sorry about changing them again; this should be the last time. Thanks!

**Comment by spencerlachance** [comment]
If you take this request over to https://github.com/spencerlachance/cs4500a1part2/issues/11 and get those guys to agree on it, I'll change them.

**Comment by destae** [comment]
We are using chases object string so feel free to close this out!
