### ISSUE TITLE
get_queue_length return size_t instead of int

### ISSUE THREAD

**Issue by destae** [spencerlachance/cs4500a1part2#19]
Hey you all can we request that your queue length function returns a size_t for consistency. Also it should be size_t because you cannot have a negative length. Thanks!

**Comment by spencerlachance** [comment]
Did you see #16 ?

I'm hesitant to change it unless there's agreement between everyone.

**Comment by ciarrapeters** [comment]
We are personally fine not changing it. I think both ideas make sense, but right now our implementation is using int, and I think we are not going to be pulling the repos any more today since the assignment is due in 8 hours and we are finished.

**Comment by spencerlachance** [comment]
Sounds good, closing
