### ISSUE TITLE
Reconcile

### ISSUE THREAD

**Issue by ZiyiPeng** [spencerlachance/cs4500a1part2#2]
We are currently trying to reconcile the differences between object.h and string.h between the three teams. 
I think the easiest way is to only add basic functionalities to object and string class
These methods should be enough to implement all data structures in the assignment

object:
virtual size_t hash()
virtual bool equals(Object* object)

String:
int compareTo()
String* concat(String* other)

**Comment by spencerlachance** [comment]
Ok if that's all you want...

I updated the spec

**Comment by spencerlachance** [comment]
Just updated the tests too to reflect the changes

**Comment by spencerlachance** [comment]
FYI it seems like Prof. Vitek's Object and String specs are the more popular choice, so I updated mine to match his.
