### ISSUE TITLE
Enqueue specification change needed

### ISSUE THREAD

**Issue by langn** [spencerlachance/cs4500a1part2#4]
The `enqueue` method says " adds o to the front of this Queue.". We assume you mean "adds o to the back of this Queue", as this is how Queue's generally work (otherwise it is a Deque or a Stack).

**Comment by langn** [comment]
Also the `dequeue` method is reversed, it should be removing the HEAD of the queue, not the last element.

**Comment by spencerlachance** [comment]
Fixed
