### ISSUE TITLE
Test File (line 42, 75) - Syntax Issues

### ISSUE THREAD

**Issue by dxandbatista** [spencerlachance/cs4500a1part2#6]
Your test file does not compile due to various issues. The main method is missing a closing bracket. Lines 42 and 75 contain method calls with no parentheses. Please edit when possible.

**Comment by dxandbatista** [comment]
Line 49 should be 't_false' instead of 't_true'; you guys even say so in your comments when listing the current states of what p and q become after queueing and dequeuing.

**Comment by dxandbatista** [comment]
You also never call your test_string_class method in your main test method.

**Comment by dxandbatista** [comment]
Also implement the print functionality in the 'OK' method at the top, so that we know we successfully execute your tests and get through the entire main method. 

Please add a call to 'OK" at the bottom of every test. Thanks!

**Comment by dxandbatista** [comment]
Please ensure your intended queue states match the correct behavior or what enqueuing/dequeuing does to a queue. In an earlier issue that we noted, you guys reversed what enqueueing/dequeueing did which messed up some tests.

**Comment by spencerlachance** [comment]
I'm not seeing a missing closing bracket on the main method. Fixed everything else.
