### ISSUE TITLE
What exactly is `Node->remove_next()` supposed to do?

### ISSUE THREAD

**Issue by langn** [spencerlachance/cs4500a1part2#8]
The given test would imply that `remove_next()` should replace the `next` value on the given `Node` with the `next` value of the `next` node. The documentation for the `remove_next` method does not mention this behavior at all, it only says to remove the next value. 

ex.
Node 1 -> Node 2 -> Node 3
Node 1.remove_next()
Node 1 ->  Node 3

Question: what is the purpose of this method? It seems like this is a result of the confusion over what a queue's behavior should be, because there is no reason to ever remove something from the middle or the end of a queue.

**Comment by drakstik** [comment]
We dont see how our test implies remove_next() should set a new next node. The tests for remove_next() are simply checking if the next_node was indeed removed by comparing it to another node. The documentation for the remove_next() method is correct.

Example of a Node removal:

Node1.get_next() == Node2
Node2.get_next() == Node3
Node 1.remove_next()
Node1.get_next() == No Next Node
Node2.get_next() == Node3

A Node is separate from the implementation of a queue, and for the purpose of queue only the Node before the front-node should be able to have its next_node "removed". All Nodes in a queue should never be manipulated by the user, the user should only pass in an Object and queue class functions should manipulate its Nodes privately.

**Comment by langn** [comment]
Okay. Sounds good, I think we were misinterpreting the goal of that test.
