### ISSUE TITLE
Why is Node included in the spec?

### ISSUE THREAD

**Issue by maxtcruz** [spencerlachance/cs4500a1part2#9]
Node seems like an implementation detail, and it's sort of restrictive. Can it be removed from the spec?

Your pals,
Max & Sean

**Comment by spencerlachance** [comment]
You make a good point, we probably should have left it out. I'm just worried about removing it because I think other people might already be using it. They've already reached out to me about it.

**Comment by maxtcruz** [comment]
It'd probably be ok to still remove it from the spec & tests even if others are already using it. They can continue to use it as a part of their implementation, but we'd like to not be forced to use it.

**Comment by seanolly** [comment]
Node is definitely an implementation detail, and it's not necessary in the behavior interface for a Queue, could you remove?

**Comment by spencerlachance** [comment]
Alright, fair enough. I removed it.

**Comment by liujiawen0905** [comment]
You should also update the README since Node has been removed.
